### ISSUE TITLE
Sintaxis de OFFSET

### ISSUE THREAD

**Issue by livchits** [undefinedschool/notes-sql#2]
En el apartado `OFFSET` el ejemplo tiene una abreviación que, creo, no forma parte del standard y que no funciona en Postgre. La tercera línea del ejemplo debería ser:

`LIMIT 3 OFFSET 6`

**Comment by nhsz** [comment]
LIMIT no estoy seguro de q sea standard pero se usa mucho y tiene soporte en la mayoría de las dbs, la notación del ejemplo es la abreviada (http://www.sqlines.com/postgresql/limit_offset) pero lo voy a cambiar porque la otra es más explícita, gracias!

**Comment by livchits** [comment]
Sí, me sorprendió que LIMIT [no forma parte del standard](https://en.wikipedia.org/wiki/Select_(SQL)#Non-standard_syntax). Y no me expresé del todo correctamente: mi observación apuntaba al uso de la notación abreviada, en Postgres te tira un `ERROR: LIMIT #,# syntax is not supported Hint: Use separate LIMIT and OFFSET clauses. ` Llegué a eso buscando descifrarla, así que poner la forma explícita estaría genial 👍
